version: "3"
services:
  frontend_react:
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend_flask
  backend_flask:
    build: backend
    ports:
      - "127.0.0.1:5000:8000"