version: "3"
services:
  frontend_react:
    build: frontend
    ports:
      - "80:80"
      - "127.0.0.1:8000:8000"
    depends_on:
      - backend_flask
    networks:
      - app-network

  backend_flask:
    build: backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


## With this docker file, networking is setup
## If I do the following: 

## SSH into the frontend container:
## sudo docker exec -i -t 71e7ae21c06c /bin/sh
## Install curl
## apk update
## apk upgrade
## apk add curl
## curl -X POST http://backend_flask:8000/predict
## It gives the output:
## {"error":"No image passed!"}
